sudo: required
services:
  - docker

before_install:
  - docker build -t donsdgr81/docker-react -f Dockerfile.dev .

script:
  - docker run donsdgr81/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-ap-southeast-1-961320403337
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"